### PR TITLE
fix: 4959 create an initialization topic if it isn't defined

### LINKED ISSUE #4959: Guardian should create a new initialization topic if `INITIALIZATION_TOPIC_ID` is not defined
### Problem description
[Documentation mentions](https://docs.hedera.com/guardian/guardian/readme/getting-started/how-to-configure-hedera-local-node) Guardian will create a new topic if the `INITIALIZATION_TOPIC_ID` is not defined. That does not seem the case, even though the source code seems to contain a function for that in case the network is set as "localnode".

### Step to reproduce
1. Clone the Guardian repo
2. Configure the environment, set `HEDERA_NET="localnode"` and `INITIALIZATION_TOPIC_ID=""`
3. Start the Guardian, login as Standard Registry, and proceed to initialize the SR account
4. See the worker-service log for the error:

```
2025-05-20T22:38:13.185Z [WORKER.2DD84BB695,WORKER]: Task error: 89cebd23-e104-4197-b8f6-7eabad873e9d, receipt for transaction 0.0.2@1747780686.291247050 contained error status INVALID_TOPIC_ID
```

### Expected behavior
If `INITIALIZATION_TOPIC_ID` is set to null/void, the topic is automatically created.
In addition, this should be true regardless of the network configuration (i.e. mainnet, testnet, previewnet, local-node)

### PR DESCRIPTION
**Pull request by Celiant**
**Related issue(s)**:

Fixes #4959 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: guardian-service/src/app.ts [hunk 1]
```diff
@@ -285,24 +282,34 @@ Promise.all([
...
-                data: {
-                    hederaAccountId: OPERATOR_ID,
-                    hederaAccountKey: OPERATOR_KEY,
-                    dryRun: false,
-                    topicMemo: TopicMemo.getGlobalTopicMemo(),
-                    payload: { userId: null }
-                }
-            }, { priority: 10 });
+
+        if (!process.env.INITIALIZATION_TOPIC_ID || process.env.INITIALIZATION_TOPIC_ID === '' || process.env.INITIALIZATION_TOPIC_ID === undefined) {
```
Comment (Pyatakov) [inline guardian-service/src/app.ts]: Can be safely replaced with
`if (!process.env.INITIALIZATION_TOPIC_ID) { ... }`

**Review by Pyatakov — CHANGES_REQUESTED** [review]

**Review by Pyatakov — APPROVED** [review]
